apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
spec:
  selector:
    matchLabels:
      run: tripviewer-label
  replicas: 2
  template:
    metadata:
      labels:
        run: tripviewer-label
    spec:
      containers:
        - name: tripviewer
          image: registryzuh9724.azurecr.io/tripviewer:0.0.1
          ports:
            - containerPort: 8080
              protocol: TCP