apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: api-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: poi-service
          servicePort: 80
        path: /api/poi
      - backend:
          serviceName: userjava-service
          servicePort: 80
        path: /api/user-java        
      - backend:
          serviceName: userprofile-service
          servicePort: 80
        path: /api/user
      - backend:
          serviceName: trips-service
          servicePort: 80
        path: /api/trips