apiVersion: v1
kind: Service
metadata:
  name: poi-service
  labels:
    run: poi-label
spec:
  selector:
    run: poi-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer