apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: trips 
spec: 
  selector: 
    matchLabels: 
      run: trips-label 
  replicas: 2 
  template: 
    metadata: 
      labels: 
        run: trips-label 
    spec: 
      containers: 
        - name: trips 
          image: registryzuh9724.azurecr.io/poi/trips:0.0.1 
          ports: 
            - containerPort: 8080 
              protocol: TCP 
          env:
            - name: SQL_USER
              value: sqladminzUh9724
            - name: SQL_PASSWORD
              value: rX0gc3Lz8
            - name: SQL_SERVER
              value: sqlserverzuh9724.database.windows.net
            - name: SQL_DBNAME
              value: mydrivingDB
            #- name: OPENAPI_DOCS_URI
            #  value: 