apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
  namespace: web-dev
  labels:
    run: tripviewer-label
spec:
  selector:
    run: tripviewer-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP