apiVersion: v1
kind: Service
metadata:
  name: trips-service
  labels:
    run: trips-label
spec:
  selector:
    run: trips-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer