apiVersion: v1
kind: Service
metadata:
  name: userjava-service
  namespace: api-dev
  labels:
    run: userjava-label
spec:
  selector:
    run: userjava-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP