apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
  namespace: api-dev
  labels:
    run: userprofile-label
spec:
  selector:
    run: userprofile-label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP