kind: Role 
apiVersion: rbac.authorization.k8s.io/v1beta1 
metadata: 
  name: web-dev-role 
  namespace: web-dev 
rules: 
  - apiGroups: ["", "extensions", "apps"] 
    resources: ["*"] 
    verbs: ["get", "list", "watch", "update", "patch"]         