kind: RoleBinding 
apiVersion: rbac.authorization.k8s.io/v1beta1 
metadata: 
  name: web-dev-rolebinding 
  namespace: web-dev 
roleRef: 
  apiGroup: rbac.authorization.k8s.io 
  kind: Role 
  name: web-dev-role 
subjects: 
- apiGroup: rbac.authorization.k8s.io 
  kind: User 
  namespace: web-dev 
  name: "webdev@OTAPRD142ops.onmicrosoft.com"